exports.seed = function (knex) {
  return knex("breeds").insert([
    { breed: "australian shepherd" },
    { breed: "beagle" },
    { breed: "border collie" },
    { breed: "boston terrier" },
    { breed: "boxer" },
    { breed: "bulldog" },
    { breed: "cavalier king charles spaniel" },
    { breed: "chihuahua" },
    { breed: "dachshund" },
    { breed: "dalmatian" },
    { breed: "dobermann" },
    { breed: "french bulldog" },
    { breed: "german shepherd" },
    { breed: "golden retriever" },
    { breed: "great dane" },
    { breed: "labrador retriever" },
    { breed: "miniature schnauzer" },
    { breed: "mixed breed" },
    { breed: "pembroke welsh corgi" },
    { breed: "pomeranian" },
    { breed: "poodle" },
    { breed: "pug" },
    { breed: "rottweiler" },
    { breed: "shiba inu" },
    { breed: "shih tzu" },
    { breed: "siberian husky" },
    { breed: "yorkshire terrier" },
    { breed: "abyssinian" },
    { breed: "american shorthair" },
    { breed: "balinese cat" },
    { breed: "bengal cat" },
    { breed: "british longhair" },
    { breed: "british shorthair" },
    { breed: "chartreux" },
    { breed: "himalayan cat" },
    { breed: "maine coon" },
    { breed: "mixed breed" },
    { breed: "munchkin cat" },
    { breed: "persian cat" },
    { breed: "ragdoll" },
    { breed: "russian blue" },
    { breed: "scottish fold" },
    { breed: "siamese cat" },
    { breed: "snowshoe cat" },
    { breed: "sphynx cat" },
    { breed: "turkish angora" },
    { breed: 'other' }]);
};
